export const CATEGORIES_TABLE = 'categories';

export const CategoryErrorCode = {
  CODE_DUPLICATE: 'CATEGORY_CODE_DUPLICATE',
  PARENT_INVALID: 'CATEGORY_PARENT_INVALID',
  PARENT_CYCLE: 'CATEGORY_PARENT_CYCLE',
  HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
} as const;
