/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "LowStockDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "LowStockQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ReportExports": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SchedulerInvocationDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}